books/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ourbooks, name="our-books"),
    path('add_to_cart/<book_pk>',
         add_to_cart, name="add_to_cart"),
    path('add_book_to_cart/<book_pk>',
         add_book_to_cart, name="add-book-to-cart"),
    path('remove_from_cart/<book_pk>/',
         remove_from_cart, name="remove-from-cart"),
    path('update_cart/<book_pk>/<action>',
         update_cart, name="update_cart"),
    path('clear_cart/',
         clear_cart, name="clear-cart"),
    path('hx_menu_cart', hx_menu_cart, name="hx_menu_cart"),

    path('<str:bookname>/', SingleBook, name="single-book"),
]

booksstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ap-admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("our-books/", include("books.urls")),
    path("publish-book/", include("publishbooks.urls")),
    path("blogger/", include("blogger.urls")),
    path("user/", include("users.urls")),
    path("paiment/", include("paiment.urls")),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', dashboard_main, name="dashboard-main"),
    path('dashboard-books/', dashboard_books, name="dashboard-books"),
    path('dashboard-books-order-published/', dashboard_books_order_published, name="dashboard-books-order-published"),
    path('dashboard-books/add-book', add_book, name="add-book"),
    path('dashboard-books/add-catgory', add_Category, name="add-catgory"),
    path('dashboard-books/<bookname>', view_Book_PDF, name="view-Book-PDF"),
    path('dashboard-articals/', dashboard_articals, name="dashboard-articals"),
    path('dashboard-users/', dashboard_users, name="dashboard-users"),
    path('dashboard-info/', dashboard_Info, name="dashboard-info"),
    path('dashboard-info/add-state', add_States, name="add-state"),
    path('dashboard-info/add-codepromo', add_Codepromo, name="add-codepromo"),
    path('dashboard-order/', dashboard_order, name="dashboard-order"),
    path('dashboard-order/show-order/<order>/', show_order_from_notification, name="dashboard-order-notification"),
    path('<app>/<model>/<int:id>/show', show_object, name='show-object'),
    path('<app>/<model>/<int:id>/edit', edit_object, name="edit-object"),
    path('<app>/<model>/<int:id>/delete', delete_object, name="delete-object"),
]

books/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _
from users.models import *
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class BooksCategory(models.Model):
    category_name = models.CharField(
        max_length=50, verbose_name="Category Name")

    class Meta:
        verbose_name = 'نوع الكتاب'
        verbose_name_plural = 'نوع الكتب'

    def __str__(self):
        return self.category_name


class Book(models.Model):

    BOOKSTATUS = [
        ("نشر", "نشر"),
        ("قيد الانتظار", "قيد الانتظار"),
        ("مرفوض", "مرفوض"),
    ]
    YEARSCHOICES = [(str(i), str(i))
                    for i in range(1900, datetime.date.today().year)]

    book_title = models.CharField(
        max_length=100, verbose_name="Book Title")
    book_subtitle = models.CharField(
        max_length=100, verbose_name="Book Sub Title", blank=True)
    book_category = models.ForeignKey(
        BooksCategory, verbose_name="Book Category", on_delete=models.CASCADE)
    book_author = models.CharField(
        max_length=100, verbose_name="Book Author")
    Book_translator = models.CharField(
        max_length=100, verbose_name="Book Translator", blank=True)
    book_discription_summary = RichTextField(_("Book Discription Sammry"))
    book_discription = RichTextField(_("Book Discription "))
    book_status = models.CharField(max_length=20,
                                   choices=BOOKSTATUS, default=BOOKSTATUS[1], verbose_name="Book Status")
    is_published = models.BooleanField(
        verbose_name="is published", default=False)
    is_accpted = models.BooleanField(
        verbose_name="is accpted", default=False, blank=True)
    book_price = models.PositiveIntegerField(verbose_name="Book Price")
    book_picture = models.ImageField(
        upload_to='Book product', verbose_name="Book Picture", blank=True)
    book_index = models.FileField(
        upload_to="Book index", verbose_name="Book index", blank=True)
    book_PDF = models.FileField(
        upload_to="Book PDF", verbose_name="Book PDF", null=True, blank=True)
    book_date_published = models.DateField(
        blank=True, null=True, default=False)
    book_year_published = models.CharField(
        max_length=20, choices=YEARSCHOICES, verbose_name="Book Year Published")
    Book_date_add = models.DateTimeField(
        auto_now=False, auto_now_add=True)
    Book_add_by = models.ForeignKey(
        "users.User", verbose_name="Book add by", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'كتاب'
        verbose_name_plural = 'الكتب'

    def __str__(self):
        return self.book_title

    def yearpublished(self):
        return self.book_date_published.strftime('%Y')


class Comments(models.Model):
    book = models.ForeignKey(
        Book, verbose_name=_("Book"), on_delete=models.CASCADE)
    commentator_name = models.CharField(
        max_length=100, verbose_name="Commentator Name")
    commentator_email = models.EmailField(
        max_length=100, verbose_name="Commentator Email")
    commentator_rating = models.PositiveIntegerField(default=1,
                                                     validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name="Rating")
    comments_body = models.TextField(
        max_length=100, verbose_name="Commentator Rating")

    class Meta:
        verbose_name = 'تعليق'
        verbose_name_plural = 'التعليقات'

    def __str__(self):
        return self.commentator_name

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404, redirect
from books.models import *
from publishbooks.models import *
from users.models import *
from paiment.models import *
from blogger.models import *
from .forms import *
from django.apps import apps
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from django.http import HttpResponse
import os
from paiment.forms import OrderForm
from notifications.models import Notification
# Create your views here.


@user_passes_test(lambda u: u.is_superuser)
def dashboard_main(request):

    context = {
        "title": "الرئيسية",
        "book_published_number": Book.objects.filter(is_published=True).count(),
        "book_not_published_number": Book.objects.filter(is_published=False).count(),
        "user_number": User.objects.all().count(),
        "admin_number": User.objects.filter(is_superuser=True).count(),
        "all_books": Book.objects.all(),
        "all_users": User.objects.all(),
        "all_articals": Artical.objects.all(),
    }

    return render(request, 'dashboard/dashboard-main.html', context)


@user_passes_test(lambda u: u.is_superuser)
def dashboard_books(request):

    context = {
        "title": "الكتب",
        "all_books": Book.objects.all(),
        "all_Book_categories": BooksCategory.objects.all(),
    }

    return render(request, 'dashboard/dashboard-books.html', context)


@user_passes_test(lambda u: u.is_superuser)
def dashboard_books_order_published(request):
    context = {
        "title": "الكتب المطلوبة لنشر",
        "all_books": BookPublishedOrder.objects.all(),
    }

    return render(request, 'dashboard/dashboard-books-order-published.html', context)


@user_passes_test(lambda u: u.is_superuser)
def view_Book_PDF(request, bookname):

    book = get_object_or_404(Book, book_title=bookname)

    pdf_file_path = os.path.join(
        settings.BASE_DIR, 'upload', str(book.book_PDF))
    print(pdf_file_path)
    with open(pdf_file_path, 'rb') as pdf_file:
        response = HttpResponse(pdf_file.read(),
                                content_type='application/pdf')
        response['Content-Disposition'] = 'filename=some_file.pdf'
        return response


@user_passes_test(lambda u: u.is_superuser)
def dashboard_articals(request):

    context = {
        "title": "مقالات",
        "all_articals": Artical.objects.all(),
    }

    return render(request, 'dashboard/dashboard-articals.html', context)


@user_passes_test(lambda u: u.is_superuser)
def dashboard_users(request):

    context = {
        "title": "المستخدمين",
        "all_users": User.objects.all(),
    }

    return render(request, 'dashboard/dashboard-users.html', context)


@user_passes_test(lambda u: u.is_superuser)
def dashboard_Info(request):

    context = {
        "title": "معلومات الفواتير",
        "all_states": State.objects.all(),
        "all_codes": CodePromo.objects.all(),
    }

    return render(request, 'dashboard/dashboard-info.html', context)


@user_passes_test(lambda u: u.is_superuser)
def dashboard_order(request):

    context = {
        "title": "طلبات الشراء",
        "all_order": Order.objects.all(),
        "all_order_items": OrderItem.objects.all(),
    }

    return render(request, 'dashboard/dashboard-order.html', context)


@user_passes_test(lambda u: u.is_superuser)
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            object = form.save(commit=False)
            object.Book_add_by = request.user
            print(form.errors)
            object.save()
            return redirect('dashboard-main')
    else:
        form = BookForm()

    context = {
        "title": "أضق كتابا",
        "form": form,
    }
    return render(request, 'dashboard/create-objects/add-book.html', context)


@user_passes_test(lambda u: u.is_superuser)
def add_Category(request):
    if request.method == 'POST':
        form = BookCategoresForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard-books')
    else:
        form = BookCategoresForm()

    context = {
        "title": "أضق نوعا جديد من الكتب",
        "form": form,
    }
    return render(request, 'dashboard/create-objects/add-category.html', context)


@user_passes_test(lambda u: u.is_superuser)
def add_States(request):
    if request.method == 'POST':
        form = StatesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard-info')
    else:
        form = StatesForm()

    context = {
        "title": "أضق ولاية جديدة",
        "form": form,
    }
    return render(request, 'dashboard/create-objects/add-category.html', context)


@user_passes_test(lambda u: u.is_superuser)
def add_Codepromo(request):
    if request.method == 'POST':
        form = CodePromoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard-info')
    else:
        form = CodePromoForm()

    context = {
        "title": "أضق كود التخفيض",
        "form": form,
    }
    return render(request, 'dashboard/create-objects/add-category.html', context)


@user_passes_test(lambda u: u.is_superuser)
def edit_object(request, app, model, id):
    print(app)
    print(model)
    print(id)

    model_classes = {
        'book': (Book, BookForm),
        'user': (User, UserForm),
        'artical': (Artical, ArticalForm),
        'bookscategory': (BooksCategory, BookCategoresForm),
        'state': (State, StatesForm),
        'codepromo': (CodePromo, CodePromoForm),
        'order': (Order, OrderForm),
        # Add more models as needed
    }

    model_class, model_form = model_classes.get(model.lower())

    # if not model_class:
    #     return redirect('error_page')

    instance = get_object_or_404(model_class, pk=id)

    if request.method == 'POST':
        form = model_form(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            if model_form._meta.model == Artical:
                if request.POST.get("artical_status") == "نشر" or request.POST.get("artical_status") == "مرفوض":
                    html = render_to_string("emails/email-articals-status.html", {
                        "title": str(instance),
                        "link": str(instance).replace(' ', '-'),
                        "status": request.POST.get("artical_status"),
                        "reason_of_rejcted": request.POST.get("reason_of_reject")
                    })
                    send_mail('contact me', "Confirm Your Email Address", "bouchouichaaek97@gmail.com",
                              [instance.artical_author.email], html_message=html)

            return redirect('dashboard-main')
    else:
        form = model_form(instance=instance)

    context = {
        "form": form,
        "title": str(instance) + "| عدل ",
        "instance_title": instance,
        "object_name": model_class._meta.verbose_name.title(),
    }

    return render(request, 'dashboard/edit-object.html', context)


@user_passes_test(lambda u: u.is_superuser)
def delete_object(request, app, model, id):

    model_classes = {
        'book': (Book, BookForm),
        'user': (User, UserForm),
        'artical': (Artical, ArticalForm),
        'bookscategory': (BooksCategory, BookCategoresForm),
        'state': (State, StatesForm),
        'codepromo': (CodePromo, CodePromoForm),
        'order': (Order, OrderForm),
    }
    model_class, model_form = model_classes.get(model.lower())

    instance = get_object_or_404(model_class, pk=id)

    if request.method == 'POST':
        instance.delete()
        return redirect('dashboard-main')

    context = {
        "title": "هل انت متأكد ؟",
        "instance_title": instance,
        "object_name": model_class._meta.verbose_name.title(),

    }
    return render(request, 'dashboard/delete-object.html', context)


@user_passes_test(lambda u: u.is_superuser)
def show_object(request,app, model, id):
    model_classes = {
        'book': (Book, BookForm),
        'user': (User, UserForm),
        'artical': (Artical, ArticalForm),
        'bookscategory': (BooksCategory, BookCategoresForm),
        'state': (State, StatesForm),
        'codepromo': (CodePromo, CodePromoForm),
        'order': (Order, OrderForm),
    }
    model_class, model_form = model_classes.get(model.lower())
    instance = get_object_or_404(model_class, pk=id)
    context = {
        "title": str(instance) + "| عرض ",
        "instance": instance,
        "object_name": model_class._meta.verbose_name.title(),
    }
    if model== "order":
      notification = Notification.objects.get(order=instance.pk)
      notification.viewed = True
      notification.save()
      template = "dashboard/show-objects/show-order.html"
      order_items = OrderItem.objects.filter(order=instance)
      context["order_items"] = order_items

  
    return render(request,template,context)


def show_order_from_notification(request,order):
    order = get_object_or_404(Order, pk=order)
    notification = Notification.objects.get(order=order.pk)
    notification.viewed = True
    notification.save()
    order_items = OrderItem.objects.filter(order=order)
    context = {
        "order":order,
        "order_items":order_items,
        "title": str(order) + "| عرض ",

    }
    
    return render(request,"dashboard/show-objects/show-order-customized.html",context)

templates/dashboard/dashboard-articals.html
{% extends 'dashboard/dashboard-base.html' %}
{% load static %}
{% load filters %}

{% block AllArticals %} 

<div class="section-box articals mt-4">
    <h1 class="title-overview fs-3 fw-bold pb-3 px-3">المقالات </h1>
    <div class="table-responsive">
        <table class="table table-striped table-hover mt-4 text-center table-bordered">
            <th class="text-uppercase ">#</th>
            <th class="text-uppercase ">عنوان المقال</th>
            <th class="text-uppercase ">الكاتب</th>
            <th class="text-uppercase ">نوع المقال</th>
            <th class="text-uppercase ">الحالة</th>
            <th class="text-uppercase ">سبب الرفض</th>
            <th class="text-uppercase text-center">إطلع على المقال</th>
            <th class="text-uppercase text-center">تعديل</th>
            <th class="text-uppercase text-center">حذف</th>


            </tr>
            {% for artical in all_articals %}
            <tr>
                <th class="text-uppercase ">{{artical.pk}}</th>
                
                <td class="text-uppercase text-start">{{artical.artical_title}}</td>
                <td class="text-uppercase">{{artical.artical_author.first_name}} {{artical.artical_author.last_name}}</td>
                <td class=" text-uppercase">{{artical.artical_category}}</td>
                <td class="text-uppercase {% if artical.artical_status == "نشر" %} publiched {% elif artical.artical_status ==  "قيد الانتظار" %} pending {% elif artical.artical_status ==  "مرفوض" %} rejected {% endif %} fw-medium">{{artical.artical_status}}</td>
                <td class=" text-uppercase">{{artical.reason_of_reject}}</td>
                <td class="text-uppercase text-center">
                    <a href="{% url 'single-artical' artical.artical_title %}" target="_blank">إطلع على المقال</a>
                </td>
                <td class="text-uppercase text-center">
                    <a class="edit" href="{% url 'edit-object' artical|app_name artical|model_name artical.pk%}">تعديل</a>
                    
                </td>
                <td class="text-uppercase text-center">
                    <a class="delete" href="{% url 'delete-object' artical|app_name artical|model_name artical.pk%}">حذف</a>        
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock AllArticals%}

templates/dashboard/dashboard-base.html
{% load static %}
{% load filters %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="icon" href="{% static 'img/logoipsum-299.svg' %}">
    <link rel="stylesheet" href="{% static 'css/alqabas.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
        integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</head>

<body class="body">


    <div class="dashboard main m-lg-4">
        <div class="container-fluid">
            <div class="row justify-content-center align-items-start g-4">
                <div class="col-12 col-sm-2 col-lg-3 ">
                    <div class="dashboard-side-bar bg-white">
                        <div class="logo text-center pt-5 pb-3">
                            <img src="{% static "img/logoipsum-299.svg" %}" alt="" srcset="">
                        </div>
                        <div class="text-title text-center pb-5">
                            <h1 class="fw-bold">لوحة التحكم</h1>
                        </div>
                        <div class="links pb-5">
                            <ul>
                                <li class="{% if request.resolver_match.url_name == 'dashboard-main' %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url 'dashboard-main' %}"><i
                                            class="fa-solid fa-gauge"></i><span>الرئيسية</span></a>
                                </li>
                                <li class="{% if  "/dashboard-books/" in request.path %} active {% endif %}">

                                    <a class="text-decoration-none" href="{% url 'dashboard-books' %}"><i
                                            class="fa-solid fa-book"></i><span>الكتب</span></a>
                                </li>
                                <li class="{% if  "/dashboard-books-order-published" in request.path %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url "dashboard-books-order-published" %}">
                                        <i class="fa-solid fa-book-medical"></i>
                                        <span>الكتب المطلوبة لنشر</span></a>
                                </li>
                                <li class="{% if  "/dashboard-articals" in request.path %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url 'dashboard-articals' %}"> <i
                                            class="fa-solid fa-newspaper"></i><span>المقالات</span></a>
                                </li>
                                <li class="{% if  "/dashboard-users" in request.path %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url 'dashboard-users' %}"> <i
                                            class="fa-solid fa-users"></i><span>المستخدمين</span></a>
                                </li>
                                <li class="{% if  "/dashboard-info" in request.path %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url 'dashboard-info' %}">
                                        <i class="fa-solid fa-file-invoice"></i>
                                    </i><span>معلومات الفواتير</span></a>
                                </li>
                                <li class="{% if  "/dashboard-order" in request.path %} active {% endif %}">
                                    <a class="text-decoration-none" href="{% url "dashboard-order" %}"><i
                                            class="fa-solid fa-sack-dollar"></i><span>طلبات الشراء</span></a>
                                </li>
                                <li>
                                    <a class="text-decoration-none" href="{% url 'logout' %}"> <i
                                            class="fa-solid fa-right-from-bracket"></i>
                                        <span>تسجيل الخروج</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-10 col-lg-9">
                    <div class="section-box header d-flex justify-content-between align-items-center">
                        <div class="search-bar">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <input type="search" name="" id="" placeholder="ابحث هنا ...">
                        </div>
                        <div class="user-noti d-flex justify-content-between align-items-center">
                            <a class="return-to-site" href="{% url 'home' %}">
                                العودة إلى الموقع
                            </a>
                            <div class="">
                                <a class="position-relative" onclick="toggleNotifi()"><span id="notifications-count"></span><i
                                        class="fa-solid fa-bell fa-xl"></i></a>
                                        <div class="notifi-box" id="box">
                                            <h2>التنبيهات : <span class="text-black fw-bold" id="notifications-count-text">0</span>  </h2>
                                            <div class="notifications-container">
                                                
                                            </div>
                                        </div>
                                    
    
                                <a href="">
                                    {% if request.user.picture %}
                                    <img style="width:40px; border-radius: 50%;border: 3px solid var(--primary-color);padding: 2px;"  src="{{request.user.picture.url}}" alt="">
                                    {% else %}
                                    <i class="fa-solid fa-circle-user fa-xl p-0"></i>
                                    {% endif %}
                                </a>
                            </div>
                        </div>
                    </div>
                    {% block OverView %}               
                    {% endblock OverView%}
                    {% block AllBooks %}               
                    {% endblock AllBooks%}
                    {% block AllBooksOrderPublished %}               
                    {% endblock AllBooksOrderPublished%}
                    {% block AllBooksCategories %}           
                    {% endblock AllBooksCategories%}
                    {% block AllUser %}               
                    {% endblock AllUser%}
                    {% block AllstatesInfo %}           
                    {% endblock AllstatesInfo%}
                    {% block AllCodePromo %}           
                    {% endblock AllCodePromo%}
                    {% block AllArticals %}               
                    {% endblock AllArticals%}
                    {% block AllOrders %}               
                    {% endblock AllOrders%}
                    {% block AddNewCategory %}               
                    {% endblock AddNewCategory%}
                    {% block EditObject %}               
                    {% endblock EditObject%}
                    {% block DeleteObject %}               
                    {% endblock DeleteObject%}
                    {% block ShowObject %}               
                    {% endblock ShowObject%}
                </div>
            </div>
        </div>
    </div>

    <script>
        let url = `ws://${window.location.host}/ws/notifications/`
        var ws = new WebSocket(url);
        let notifications = []

        ws.onopen = function() {
            console.log('WebSocket connection opened');
        };

        ws.onmessage = function(event) {
            var data = JSON.parse(event.data);
            notifications.push(data);
            let notifications_count = document.querySelector("#notifications-count")
            let notifications_count_text = document.querySelector("#notifications-count-text")
            let notifications_container = document.querySelector(".notifications-container")
            notifications_container.innerHTML = "";
            notifications_count.textContent = notifications.length
            notifications_count_text.textContent = notifications.length
            if(notifications.length > 0){
                notifications_count.style.backgroundColor = "#724215"
            }
            notifications.forEach((element) => {
                var box = document.createElement("div");
                box.classList.add("notifi-item");
              //  console.log(element)
                if(!element.viewed){
                    box.style.backgroundColor = "#378fe933" 
                }
                const dynamicUrl = "{% url 'dashboard-order-notification' 'parameter' %}".replace('parameter', element.order_id);

                box.innerHTML = `
                <div class="text">
                    <a href="${dynamicUrl}" target="_blank"><p>${element.notification}</p></a>
                  </div> 
                 `
                 notifications_container.append(box)
            }
            )
            
        };

        ws.onclose = function() {
            console.log('WebSocket connection closed');
        };

        $(function () {
          $("#id_book_date_published").datepicker({
            format: "yyyy-mm-dd",
          });
        });


        var box  = document.getElementById('box');
        var down = false;
        
        
        function toggleNotifi(){
            if (down) {
                box.style.height  = '0px';
                box.style.opacity = 0;
                down = false;
            }else {
                box.style.height  = '370px';
                box.style.opacity = 1;
                down = true;
            }
        }

      </script>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/alqabas.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>

</body>

</html>

templates/dashboard/delete-object.html
{% extends 'dashboard/dashboard-base.html' %}
{% load static %}



{% block DeleteObject %}     
<div class="section-box books-list mt-4">
    <h1 class="title-overview fs-3 fw-bold px-3">هل انت متأكد من أنك تريد حذف {{object_name}}
        <span style="color: var(--primary-color);">{% if instance_title.first_name %} {{instance_title.first_name}} {{instance_title.last_name}} {% else %} {{instance_title}} {% endif %}</span>
        ؟
    </h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="button text-end d-flex justify-content-end align-items-center gap-3">
            <a class="btn cancel" href="{% url 'dashboard-main' %}">إلغاء</a>
            <input class="btn save" type="submit" value="حذف">
        </div>
    </form>
</div>          
{% endblock DeleteObject%}